### PR TITLE
QA module

### PR DESCRIPTION
**Pull request by vamman311**
Added a QA.jsx file and a constituent component.

Please review the file and let me know if it is okay to merge this into our development branch.

### CODE REVIEW

**Review by sterno2510 — APPROVED** [review]
Looks good!  Ok to merge!

**Review by mariovtristan — APPROVED** [review]
Looks good to me

**Comment by vamman311** [comment]
Changed the export statement, thanks.  Is it ready to go?

**Review by huongnguyen04 — APPROVED** [review]
Looks good! Ready to merge.

**Pull request merged**
